package com.homedao.dao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.homedao.bean.Attachment;

import com.homedao.dao.AttachmentDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig attachmentDaoConfig;

    private final AttachmentDao attachmentDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        attachmentDaoConfig = daoConfigMap.get(AttachmentDao.class).clone();
        attachmentDaoConfig.initIdentityScope(type);

        attachmentDao = new AttachmentDao(attachmentDaoConfig, this);

        registerDao(Attachment.class, attachmentDao);
    }
    
    public void clear() {
        attachmentDaoConfig.getIdentityScope().clear();
    }

    public AttachmentDao getAttachmentDao() {
        return attachmentDao;
    }

}
